#!/usr/bin/env bash

function error_handler() {
  >&2 echo "Exited with BAD EXIT CODE '${2}' in ${0} script at line: ${1}."
  exit "$2"
}
trap 'error_handler ${LINENO} $?' ERR
set -o errtrace -o errexit -o nounset -o pipefail

function send_curl() {
  local partition_topic=$1
  local payload=$2
  curl -v -f -s -X POST -H Content-type:application/json --data '{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "post_waku_v2_relay_v1_message",
    "params": ["", {
        "payload": "'$payload'",
        "contentTopic": "'$partition_topic'",
        "version": 1
    }]
    }' http://localhost:8545

  # curl -v -f -s -X POST -H Content-type:application/json --data '{
  #   "params": ["", {
  #       "payload": "'$payload'",
  #       "contentTopic": "contentTopicGoesHere",
  #       "timestamp": 1257894000000000000,
  #       "version": 1
  #   }]
  #   }' http://localhost:8545/waku/v2/relay/v1/message
}

go build waku/client
content=$(./client)
partition_topic=$(awk -F ':' '{print $1}' <<<"$content")
payload_string=$(awk -F ':' '{print $2}' <<<"$content")
send_curl "$partition_topic" "$payload_string"
